# SPDX-License-Identifier: MIT
---
# Put internal variables here with Debian specific values.

__keyserver_name: valkey
__keyserver_conf_path: /etc/valkey
__keyserver_conf_file: valkey.conf

__keyserver_packages:
  - valkey-tools
  - valkey-server

__keyserver_packages_extra: []

__keyserver_loaded_modules: []
