# SPDX-License-Identifier: MIT
---

__pcp_packages:
  - pcp

__pcp_packages_extra: []

__pcp_conf: /etc/pcp.conf
__pcp_pmcd_conf: /etc/pcp/pmcd/pmcd.conf
__pcp_pmie_control_path: /etc/pcp/pmie/control.d
__pcp_pmlogger_control_path: /etc/pcp/pmlogger/control.d
__pcp_explicit_labels_path: /etc/pcp/labels
__pcp_implicit_labels_path: /etc/pcp/labels/optional
__pcp_agents_path: /var/lib/pcp/pmdas
