---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configuration tasks.
- include_tasks: pmcd.yml

- include_tasks: pmie.yml

- include_tasks: pmlogger.yml

- include_tasks: pmproxy.yml
  when: pcp_rest_api == 'true'
