# SPDX-License-Identifier: MIT
---

dependencies: []

galaxy_info:
  author: performancecopilot
  description: Performance Co-Pilot Redis role
  role_name: redis
  company: pcp.io
  license: "license (MIT)"
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - pcp
    - redis
    - metrics
    - analysis
    - monitoring
    - timeseries
    - performance
    - lightweight
    - visualization
    - instrumentation
