# SPDX-License-Identifier: MIT
---

- name: Set platform/version specific variables
  include_vars: "{{ item }}.yml"
  loop:
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: item is file

- name: Ensure PCP SQL Server agent is configured
  template:
    src: mssql.conf.j2
    dest: "{{ __mssql_conf }}"
    mode: 0600
  become: yes

- name: Ensure PCP SQL Server metrics are available
  import_role:
    name: pcp
  vars:
    pcp_optional_agents: [mssql]
    pcp_optional_packages: {{ __mssql_packages_extra }}
