# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
- name: Set platform/version specific variables
  include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/default.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['os_family'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  when: item is file
# yamllint enable rule:line-length

- name: Determine if system is ostree and set flag
  when: not __ansible_pcp_is_ostree is defined
  block:
    - name: Check if system is ostree
      stat:
        path: /run/ostree-booted
      register: __ostree_booted_stat

    - name: Set flag to indicate system is ostree
      set_fact:
        __ansible_pcp_is_ostree: "{{ __ostree_booted_stat.stat.exists }}"

- name: Establish SQL Server metrics package names
  set_fact:
    __mssql_packages_extra: "{{ __mssql_packages_pcp }}"
  when: mssql_metrics_provider == 'pcp'

- name: Install needed SQL Server metrics packages
  package:
    name: "{{ __mssql_packages_extra }}"
    state: present
    use: "{{ (__ansible_pcp_is_ostree | d(false)) |
             ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
  when: __mssql_packages_extra | d([])

- name: Ensure PCP SQL Server agent configuration directory exists
  file:
    path: "{{ __mssql_conf_dir }}"
    state: directory
    mode: "0755"
  when: mssql_metrics_provider == 'pcp'

- name: Ensure PCP SQL Server agent is configured
  template:
    src: mssql.conf.j2
    dest: "{{ __mssql_conf }}"
    follow: true
    mode: "0600"
  when: mssql_metrics_provider == 'pcp'

- name: Ensure SQL Server performance rule group directory exists
  file:
    path: "{{ __mssql_pmieconf_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: mssql_metrics_provider == 'pcp'

- name: Ensure SQL Server performance rule group link directory exists
  file:
    path: "{{ __mssql_pmieconf_link_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: mssql_metrics_provider == 'pcp'

- name: Ensure SQL Server performance rules are installed for targeted hosts
  copy:
    src: "files/{{ item }}"
    dest: "{{ __mssql_pmieconf_path }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ __mssql_pmieconf_rules | default([]) }}"
  when: mssql_metrics_provider == 'pcp'

- name: Ensure SQL Server rules symlinks have been created for targeted hosts
  file:
    src: "{{ __mssql_pmieconf_path }}/{{ item }}"
    dest: "{{ __mssql_pmieconf_link_path }}/{{ item }}"
    state: link
    force: true
  loop: "{{ __mssql_pmieconf_rules | default([]) }}"
  when: mssql_metrics_provider == 'pcp'
