# SPDX-License-Identifier: MIT
---
# Put internal variables here with CentOS 6 specific values.

__grafana_keyserver_datasource_name: Redis
__grafana_keyserver_datasource_type: pcp-redis-datasource
__grafana_keyserver_datasource_alttype: performancecopilot-redis-datasource
__grafana_packages_extra: []
